# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    #- name: Test
    #  run: go test -v ./...

    - uses: actions/upload-artifact@v4
      with:
        name: symmetrical-adventure-linux-amd64
        path: symmetrical-adventure
        compression-level: 6 # GNU Gzip
